name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Assure-toi que la version correspond à ce que ton projet utilise

    - name: Install dependencies
      run: npm install
      working-directory: ./backend  # Spécifie le répertoire où se trouve le package.json

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@88.173.47.125 -p 17524 << 'EOF'
          cd /home/my_build_site/my_build_site
          git pull origin main
          npm install
          pm2 restart all  # Si tu utilises pm2 pour gérer ton serveur
        EOF
