name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Assure-toi que la version correspond à ce que ton projet utilise

    - name: Install dependencies
      run: npm install
      working-directory: ./backend  # Spécifie le répertoire où se trouve le package.json

    - name: Run tests
      run: npm test
      working-directory: ./backend  # Spécifie le répertoire où se trouvent les tests

    - name: Build the project
      run: npm run build
      working-directory: ./backend  # Spécifie le répertoire où se trouve le script de build

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
          cd /chemin/vers/ton/projet
          git pull origin main
          npm install
          pm2 restart all  # Si tu utilises pm2 pour gérer ton serveur
        EOF
