name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy via SSH
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@88.173.47.125 -p 17524 << 'EOF'
          cd /home/my_build_site/my_build_site
          git pull origin main
          cd backend
          node server.js
        EOF
