name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    # - name: Run tests
    #   run: npm test
    #   working-directory: ./backend

    - name: Build the project
      run: npm run build
      working-directory: ./backend

    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key root@88.173.47.125 -p 17524 << 'EOF'
          cd /chemin/vers/ton/projet
          git pull origin main
          npm install
          pm2 restart all
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clean up
      run: rm ssh_key
